name: Coding Standards
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-suite:
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.2','7.3','7.4','8.0','8.1','8.2','8.3']

    name: Coding standards test
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'chore(') }}
    env:
      EXTENSION_PATH: "my-code/whm-plugin"

    steps:
      - name: Install DDEV
        run: |
          # @see https://ddev.readthedocs.io/en/stable/#installationupgrade-script-linux-and-macos-armarm64-and-amd64-architectures
          curl -fsSL https://apt.fury.io/drud/gpg.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/ddev.gpg > /dev/null
          echo "deb [signed-by=/etc/apt/trusted.gpg.d/ddev.gpg] https://apt.fury.io/drud/ * *" | sudo tee /etc/apt/sources.list.d/ddev.list
          sudo apt-get -q update
          sudo apt-get -q -y install libnss3-tools ddev
          mkcert -install
          ddev config global --instrumentation-opt-in=false --omit-containers=ddev-ssh-agent

      - name: Create empty PHP DDEV project
        run: ddev config --project-type=php --project-name=crowdsec-whm-plugin  --php-version=${{ matrix.php-version }}

      - name: Add-ons install
        run: ddev get julienloizelet/ddev-tools

      - name: Start DDEV  with PHP ${{ matrix.php-version }}
        run: ddev start

      - name: Some DEBUG information
        run: |
          ddev --version
          ddev exec php -v

      - name: Clone sources
        uses: actions/checkout@v4
        with:
          path: ${{env.EXTENSION_PATH}}

      - name: Install coding tools
        run: |
          ddev composer update --working-dir ./${{env.EXTENSION_PATH}}/tools

      - name: Run PHPCS
        run: |
          ddev phpcs ./${{env.EXTENSION_PATH}}/tools ${{env.EXTENSION_PATH}}/plugin/src PSR12
          ddev phpcs ./${{env.EXTENSION_PATH}}/tools ${{env.EXTENSION_PATH}}/plugin/endpoints PSR12

      - name: Run PHPMD
        run: |
          ddev phpmd ./${{env.EXTENSION_PATH}}/tools phpmd/rulesets.xml ../plugin/src
          ddev phpmd ./${{env.EXTENSION_PATH}}//tools phpmd/rulesets.xml ../plugin/endpoints

      - name: Run PHPSTAN
        run: |
          ddev phpstan /var/www/html/${{env.EXTENSION_PATH}}/tools phpstan/phpstan.neon /var/www/html/${{env.EXTENSION_PATH}}/plugin/src
          ddev phpstan /var/www/html/${{env.EXTENSION_PATH}}/tools phpstan/phpstan-endpoints.neon /var/www/html/${{env.EXTENSION_PATH}}/plugin/endpoints

      - name: Run PSALM
        run: |
          ddev psalm ./${{env.EXTENSION_PATH}}/tools /var/www/html/${{env.EXTENSION_PATH}}/tools/psalm
          ddev psalm ./${{env.EXTENSION_PATH}}/tools ./${{env.EXTENSION_PATH}}/tools/psalm/endpoints

